# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adbfd0b6711e464671e0de1df416b7e3"
name = "Checkout Blocks"
handle = "checkout-blocks-43"
application_url = "https://maintains-pct-combination-sitting.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://maintains-pct-combination-sitting.trycloudflare.com/auth/callback",
  "https://maintains-pct-combination-sitting.trycloudflare.com/auth/shopify/callback",
  "https://maintains-pct-combination-sitting.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
